### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Risa123** [OpenPrograms/MiscPrograms#9]
none

**Comment by PackmanDude** [comment]
> none
> 

смажені нігери

**Comment by xandaaah** [comment]
?

**Comment by Risa123** [comment]
I guess I realized that what I thought was a bug was a feature. Can't tell you more since as you can see this thread is 6 years old. I do not even play minecraft anymore, in fact.

**Comment by xandaaah** [comment]
Oh

**Comment by Risa123** [comment]
Is that a surprise ?

**Comment by xandaaah** [comment]
Yes

**Comment by Risa123** [comment]
Why do you find surprising about someone not doing something anymore ?

**Comment by xandaaah** [comment]
I am not suprised about that. I am suprised about the fact this issue is 6 years old.

**Comment by xandaaah** [comment]
I have never seen an issue that old.
